// Adapted from the Three.js webgl_gpgpu_birds_gltf example (MIT).
import * as THREE from './vendor/three.module.js';
import {GPUComputationRenderer} from './vendor/GPUComputationRenderer.js';

const positionShader=`uniform float delta;void main(){vec2 uv=gl_FragCoord.xy/resolution.xy;vec4 p=texture2D(texturePosition,uv);vec3 v=texture2D(textureVelocity,uv).xyz;float phase=mod(p.w+delta+length(v.xz)*delta*3.+max(v.y,0.)*delta*6.,62.83);gl_FragColor=vec4(p.xyz+v*delta*15.,phase);}`;
const velocityShader=`uniform float delta;uniform float separationDistance;uniform float alignmentDistance;uniform float cohesionDistance;uniform vec3 predator;const float width=resolution.x;const float height=resolution.y;const float PI=3.141592653589793;const float PI2=PI*2.;const float UPPER_BOUNDS=BOUNDS;const float SPEED_LIMIT=9.;void main(){float zone=separationDistance+alignmentDistance+cohesionDistance;float sep=separationDistance/zone;float align=(separationDistance+alignmentDistance)/zone;float zone2=zone*zone;vec2 uv=gl_FragCoord.xy/resolution.xy;vec3 selfPos=texture2D(texturePosition,uv).xyz;vec3 velocity=texture2D(textureVelocity,uv).xyz;vec3 dir=predator*UPPER_BOUNDS-selfPos;dir.z=0.;float dist=length(dir);if(dist<150.)velocity+=normalize(dir)*(dist*dist/(150.*150.)-1.)*delta*100.;dir=selfPos;dir.y*=2.5;velocity-=normalize(dir)*delta*5.;for(float y=0.;y<height;y++){for(float x=0.;x<width;x++){vec2 ref=vec2(x+.5,y+.5)/resolution.xy;vec3 otherPos=texture2D(texturePosition,ref).xyz;dir=otherPos-selfPos;dist=length(dir);if(dist<.0001)continue;float d2=dist*dist;if(d2>zone2)continue;float pct=d2/zone2;if(pct<sep){velocity-=normalize(dir)*(sep/pct-1.)*delta;}else if(pct<align){vec3 otherVel=texture2D(textureVelocity,ref).xyz;float q=(pct-sep)/(align-sep);velocity+=normalize(otherVel)*(.5-cos(q*PI2)*.5+.5)*delta;}else{float q=(pct-align)/(1.-align);velocity+=normalize(dir)*(.5-(cos(q*PI2)*-.5+.5))*delta;}}}if(length(velocity)>SPEED_LIMIT)velocity=normalize(velocity)*SPEED_LIMIT;gl_FragColor=vec4(velocity,1.);}`;
const pow2=n=>2**Math.ceil(Math.log2(n));

export function createGpuFlock({renderer,scene,gltf,width=32,scale=.022}){
 const source=[];gltf.scene.traverse(o=>{if(o.isMesh)source.push(o)});const bird=source[0];if(!bird?.geometry?.index||!gltf.animations?.length)throw Error('This bird has no indexed animated mesh');
 const geo=bird.geometry,pos=geo.getAttribute('position'),morph=geo.morphAttributes.position;if(!morph?.length)throw Error('This bird has no morph animation');
 const frames=Math.round(gltf.animations[0].duration*60),tw=pow2(pos.count),th=pow2(frames),animation=new Float32Array(4*tw*th);
 for(let x=0;x<tw;x++)for(let y=0;y<th;y++){if(y>=frames)continue;const off=(y*tw+x)*4,at=y/frames*morph.length,lo=Math.floor(at),hi=(lo+1)%morph.length,k=at-lo;for(let c=0;c<3;c++){const a=morph[lo].array[x*3+c],b=morph[hi].array[x*3+c];if(a!==undefined&&b!==undefined)animation[off+c]=THREE.MathUtils.lerp(a,b,k);}animation[off+3]=1;}
 const animationTexture=new THREE.DataTexture(animation,tw,th,THREE.RGBAFormat,THREE.FloatType);animationTexture.needsUpdate=true;
 const count=width*width,vertices=[],references=[],seeds=[],indices=[];
 for(let i=0;i<count;i++){const u=(i%width)/width,v=Math.floor(i/width)/width,r=Math.random();for(let j=0;j<pos.count;j++){vertices.push(pos.getX(j),pos.getY(j),pos.getZ(j));references.push(u,v,j/tw,frames/th);seeds.push(i,r,Math.random(),Math.random());}const offset=i*pos.count;for(let j=0;j<geo.index.count;j++)indices.push(geo.index.array[j]+offset);}
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setAttribute('reference',new THREE.Float32BufferAttribute(references,4));geometry.setAttribute('seeds',new THREE.Float32BufferAttribute(seeds,4));geometry.setIndex(indices);
 let shader;const material=new THREE.MeshStandardMaterial({color:bird.material?.color||0xffa0b5,flatShading:true,roughness:.88,metalness:0});material.onBeforeCompile=s=>{shader=s;s.uniforms.texturePosition={value:null};s.uniforms.textureVelocity={value:null};s.uniforms.textureAnimation={value:animationTexture};s.uniforms.time={value:0};s.uniforms.size={value:scale};s.vertexShader=s.vertexShader.replace('#define STANDARD','#define STANDARD\nattribute vec4 reference;attribute vec4 seeds;uniform sampler2D texturePosition;uniform sampler2D textureVelocity;uniform sampler2D textureAnimation;uniform float time;uniform float size;').replace('#include <begin_vertex>',`vec4 tmp=texture2D(texturePosition,reference.xy);vec3 velocity=normalize(texture2D(textureVelocity,reference.xy).xyz);vec3 wing=texture2D(textureAnimation,vec2(reference.z,mod(time+seeds.x*(.0004+seeds.y/10000.),reference.w))).xyz;vec3 newPosition=(position+wing)*(size+seeds.y*size*.2);velocity.z*=-1.;float xz=max(length(velocity.xz),.0001);float x=sqrt(max(1.-velocity.y*velocity.y,0.));mat3 ry=mat3(velocity.x/xz,0.,-velocity.z/xz,0.,1.,0.,velocity.z/xz,0.,velocity.x/xz);mat3 rz=mat3(x,velocity.y,0.,-velocity.y,x,0.,0.,0.,1.);vec3 transformed=ry*rz*newPosition+tmp.xyz;`);};
 const mesh=new THREE.Mesh(geometry,material);mesh.rotation.y=Math.PI/2;mesh.frustumCulled=false;scene.add(mesh);
 const compute=new GPUComputationRenderer(width,width,renderer),ptex=compute.createTexture(),vtex=compute.createTexture();for(let i=0;i<ptex.image.data.length;i+=4){ptex.image.data[i]=(Math.random()-.5)*310;ptex.image.data[i+1]=55+Math.random()*125;ptex.image.data[i+2]=(Math.random()-.5)*280;ptex.image.data[i+3]=Math.random()*62.;vtex.image.data[i]=(Math.random()-.5)*10;vtex.image.data[i+1]=(Math.random()-.5)*4;vtex.image.data[i+2]=(Math.random()-.5)*10;vtex.image.data[i+3]=1;}
 const vel=compute.addVariable('textureVelocity',velocityShader,vtex),position=compute.addVariable('texturePosition',positionShader,ptex);compute.setVariableDependencies(vel,[position,vel]);compute.setVariableDependencies(position,[position,vel]);vel.material.defines.BOUNDS='400.00';for(const variable of [vel,position]){variable.wrapS=THREE.RepeatWrapping;variable.wrapT=THREE.RepeatWrapping;}const vu=vel.material.uniforms,pu=position.material.uniforms;pu.delta={value:0};vu.delta={value:0};vu.separationDistance={value:20};vu.alignmentDistance={value:20};vu.cohesionDistance={value:20};vu.predator={value:new THREE.Vector3(10000,10000,0)};const error=compute.init();if(error){scene.remove(mesh);geometry.dispose();material.dispose();throw Error(error);}
 const api={mesh,count,active:count,setCount(n){api.active=Math.max(0,Math.min(count,n));geometry.setDrawRange(0,geo.index.count*api.active);},step(time,delta,predator){if(!shader)return;pu.delta.value=delta;vu.delta.value=delta;vu.predator.value.copy(predator||vu.predator.value);compute.compute();shader.uniforms.time.value=time;shader.uniforms.texturePosition.value=compute.getCurrentRenderTarget(position).texture;shader.uniforms.textureVelocity.value=compute.getCurrentRenderTarget(vel).texture;},dispose(){scene.remove(mesh);geometry.dispose();material.dispose();animationTexture.dispose();}};api.setCount(count);return api;
}
